name: chat_app
description: "vox demo â€” ChatApp. WebSocket, DI, shared state, themes."
publish_to: 'none'
version: 1.0.0

environment:
  sdk: ^3.10.8

dependencies:
  flutter:
    sdk: flutter
  vox:
    path: ../../

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  custom_lint: ^0.6.0
  vox_lint:
    path: ../../packages/vox_lint

flutter:
  uses-material-design: true
